application: mitac-cust-gcp-1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: main.API
  secure: always

- url: .*
  script: main.APPLICATION
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: 1.0

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Build files that have no effect in App Engine's runtime.
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^gulp\.js
- ^node_modules/(.*/)?
- ^bower_components/(.*/)?